name: lion_sales
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.12+12


environment:
  sdk: ">=3.0.3 <4.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  bloc: ^8.1.2
  dio: ^5.2.1+1
  rxdart: ^0.27.7
  flutter_secure_storage: 8.0.0
  connectivity_plus: ^5.0.0
  google_nav_bar: ^5.0.6
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  persistent_bottom_nav_bar: ^5.0.2
  fluttertoast: ^8.2.2
  flutter_keyboard_visibility: ^5.4.1
  pin_code_fields: ^8.0.1
  get_it: ^7.6.0
  dropdown_button2: ^2.3.9
  intl: ^0.18.1
  firebase_core: ^2.17.0
  firebase_crashlytics: ^3.3.7
#  package_info_plus: ^4.1.0
  url_launcher: ^6.1.14
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon_o"
  ios: true
  image_path: "assets/icons/launcher_icon_o.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
