// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY59WUNfFAey5h6retkRpzKHpThDjTjU4',
    appId: '1:126881212301:web:8f24fb0678d2a76c44ffc4',
    messagingSenderId: '126881212301',
    projectId: 'lionsales-5b544',
    authDomain: 'lionsales-5b544.firebaseapp.com',
    storageBucket: 'lionsales-5b544.appspot.com',
    measurementId: 'G-QMYZPYNM09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg105SddD0ixsNot90y-6OsSQyv4RzlmQ',
    appId: '1:126881212301:android:503106db875febf044ffc4',
    messagingSenderId: '126881212301',
    projectId: 'lionsales-5b544',
    storageBucket: 'lionsales-5b544.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAOPhnbUIFrfvk7Z4bUc6B9SV4sUBocL0',
    appId: '1:126881212301:ios:e43e205a148f5d2d44ffc4',
    messagingSenderId: '126881212301',
    projectId: 'lionsales-5b544',
    storageBucket: 'lionsales-5b544.appspot.com',
    iosBundleId: 'com.lionSales.lionSale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAOPhnbUIFrfvk7Z4bUc6B9SV4sUBocL0',
    appId: '1:126881212301:ios:2bad7c7f9822051d44ffc4',
    messagingSenderId: '126881212301',
    projectId: 'lionsales-5b544',
    storageBucket: 'lionsales-5b544.appspot.com',
    iosBundleId: 'com.example.lionSales.RunnerTests',
  );
}
